# Generate Team Workflow
# Creates custom AI agent team based on discovery requirements

name: "generate-team"
description: "Generate custom team with distinct personas and workflows based on user requirements"

# Input from discovery
input_variables:
  requirements_document: ""
  primary_task: ""
  domain: ""
  team_size_preference: ""
  key_concerns: []
  collaboration_style: ""
  required_expertise: ""
  domain_context: ""

# Working variables during generation
variables:
  # Pattern library
  loaded_patterns: []
  primary_pattern: ""
  pattern_learnings: ""

  # Agent generation
  agent_roles: []
  agent_count: 0
  generated_agents: []

  # Workflow generation
  workflow_count: 0
  generated_workflows: []

  # Team composition
  team_name: ""
  team_description: ""
  team_structure: ""
  collaboration_model: ""

  # Generation output
  generation_summary: ""
  installation_package: ""

# Metadata
metadata:
  version: "1.0"
  author: "TeamBuilder"
  created: "2025-12-02"
  tags:
    - "generation"
    - "team-creation"
    - "ai-generation"

# Outputs
outputs:
  - file: "generated-team-{{team_name}}/GENERATION_SUMMARY.md"
    description: "Summary of generated team"
    template: "template.md"

  - files: "generated-team-{{team_name}}/agents/*.md"
    description: "Individual agent files"
    count: "{{agent_count}}"

  - files: "generated-team-{{team_name}}/workflows/*"
    description: "Generated workflow files"
    count: "{{workflow_count}}"

  - file: "generated-team-{{team_name}}/config.yaml"
    description: "Team configuration"

# Agent assignment
agents:
  primary: "teambuilder"

# Settings
settings:
  max_agents: 12
  min_agents: 4
  require_coordinator: true
  require_domain_expert: true
  generate_workflows: true
  load_pattern_limit: 3
  output_directory: "_bmad/teams"

# Execution notes
execution_notes: |
  This workflow is the heart of TeamBuilder's generation engine.

  Process:
  1. Load requirements from discovery
  2. Load relevant patterns from pattern library
  3. Learn composition principles (NOT copy patterns)
  4. Define agent roles AND types (Entry-Point vs Sub-Agent)
  5. Generate distinct personas for each agent
  6. Generate Entry-Point agents as thin shells (<100 lines, no instructions section)
  7. Generate Sub-Agents with persona + focused instructions
  8. Design workflow file triads (workflow.yaml + instructions.md + template.md)
  9. Copy shared workflow files (save-session, memory-guide)
  10. Create collaboration model and team config
  11. Package team for installation
  12. Register team in BMAD manifests (CRITICAL for discoverability)
  13. Create Claude Code command stubs for Entry-Point agents ONLY
  14. Create party-mode and workflow command stubs
  15. Setup team memory file and configure .mcp.json MEMORY_FILE_PATH
  16. Trigger validation workflow

  CRITICAL ARCHITECTURE: Generated agents follow TWO patterns:
  - Entry-Point agents: Thin shells (<100 lines) with activation, menu-handlers,
    rules, persona, menu. NO instructions/working-methods/memory-protocol sections.
    All task logic lives in external workflow files.
  - Sub-Agents: Persona + focused instructions. No activation or menu.

  CRITICAL: Teams MUST be registered in manifests for Claude Code
  to discover them. Registration adds agents to agent-manifest.csv
  and team to manifest.yaml.

  CRITICAL: Only Entry-Point agents get command stubs in .claude/commands/.
  Sub-Agents are invoked via workflow file references, not slash commands.

# Manifest registration settings
manifest_registration:
  enabled: true
  agent_manifest_path: "_bmad/_config/agent-manifest.csv"
  main_manifest_path: "_bmad/_config/manifest.yaml"
  module_prefix: "teams"  # Agents registered as "teams:{team-name}"

# Claude Code command stub settings
claude_code_stubs:
  enabled: true
  base_path: ".claude/commands"
  note: "Only Entry-Point agents get command stubs. Sub-Agents do NOT."
  naming: "bmad-agent-teams-{{team_name}}-{{agent-id}}.md"
  stub_template: |
    ---
    name: '{{agent-id}}'
    description: '{{title}} - {{role_summary}}'
    disable-model-invocation: true
    ---

    You must fully embody this agent's persona and follow all activation instructions exactly as specified. NEVER break character until given an exit command.

    <agent-activation CRITICAL="TRUE">
    1. INVENTORY available MCP tools - check what's available (memory, playwright, etc.)
    2. If memory MCP is available: search_nodes for "{{team_name}}" and "general:" to load working methods
    3. If TOOL_RECOMMENDATIONS.md exists at {project-root}/_bmad/teams/{{team_name}}/TOOL_RECOMMENDATIONS.md, READ it for tool guidance
    4. READ session-context.md at {project-root}/_bmad/teams/{{team_name}}/session-context.md if it exists and has content - this is your project knowledge base
    5. LOAD the FULL agent file from {project-root}/_bmad/teams/{{team_name}}/agents/{{agent-id}}.md
    6. READ its entire contents - this is a thin shell with persona, activation, menu-handlers, rules, and menu
    7. FOLLOW every step in the <activation> section precisely
    8. DISPLAY the welcome/greeting (if session context loaded in step 4, acknowledge it: "I've loaded our session context - we were working on [summary]. Continuing from there.")
    9. PRESENT the numbered menu
    10. WAIT for user input before proceeding
    </agent-activation>

# Next workflow
next_workflow:
  path: "_bmad/teambuilder/workflows/2-generation/validate-team/workflow.yaml"
  automatic: true
  pass_variables:
    - generated_agents
    - generated_workflows
    - team_name
    - requirements_document
